name: Python CI

# When should the workflow run
on:
  push:
    branches: [ main, master, 2024/Day01 ]
  pull_request:
    branches: [ main, master ]

# Define the jobs to run
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Steps to run inside a job
    steps:
    - name: 4.1 Checkout code
      uses: actions/checkout@v4

    - name: 4.2 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 4.3 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4.4 Run linters
      run: |
        flake8 2024/ --count --select=E9,F63,F7,  F82 --show-source --statistics

    - name: 4.5 Run tests
      run: |
        pytest 2024/
